#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>
#include "vecmat.h"

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
public:

	GUIMyFrame1( wxWindow* parent );

	void Repaint();

protected:
	
	void WxPanel_Repaint( wxUpdateUIEvent& event );
	void m_button_load_geometry_click( wxCommandEvent& event );
	void Scrolls_Updated( wxScrollEvent& event );

private:

	Matrix4 makeCenter() const;
	Matrix4 makeRotationX(const double xRotation) const;
	Matrix4 makeRotationY(const double yRotation) const;
	Matrix4 makeRotationZ(const double zRotation) const;
	Matrix4 makeScale(const double x, const double y, const double zScale) const;
	Matrix4 makeTranslation(const double x, const double y, const double z) const;

};

#endif // __GUIMyFrame1__
